// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4vm4UIIvYGf3iHJTn4CdpRIGSQSiehHo',
    appId: '1:488513440701:web:6eae4f765ccd0a324f60d4',
    messagingSenderId: '488513440701',
    projectId: 'multiplayercarddemo',
    authDomain: 'multiplayercarddemo.firebaseapp.com',
    storageBucket: 'multiplayercarddemo.appspot.com',
    measurementId: 'G-2Q8C9G9FVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojmo7pt50fbXxzggobTovK72Cp_V1dn0',
    appId: '1:488513440701:android:8ba9dca8db18d7e34f60d4',
    messagingSenderId: '488513440701',
    projectId: 'multiplayercarddemo',
    storageBucket: 'multiplayercarddemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKH1_8IfD6-mb737UQ8PqIBk8kCBA7bK0',
    appId: '1:488513440701:ios:022bec9646715abe4f60d4',
    messagingSenderId: '488513440701',
    projectId: 'multiplayercarddemo',
    storageBucket: 'multiplayercarddemo.appspot.com',
    iosBundleId: 'com.example.connectFour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKH1_8IfD6-mb737UQ8PqIBk8kCBA7bK0',
    appId: '1:488513440701:ios:022bec9646715abe4f60d4',
    messagingSenderId: '488513440701',
    projectId: 'multiplayercarddemo',
    storageBucket: 'multiplayercarddemo.appspot.com',
    iosBundleId: 'com.example.connectFour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4vm4UIIvYGf3iHJTn4CdpRIGSQSiehHo',
    appId: '1:488513440701:web:30e28f807f5a032e4f60d4',
    messagingSenderId: '488513440701',
    projectId: 'multiplayercarddemo',
    authDomain: 'multiplayercarddemo.firebaseapp.com',
    storageBucket: 'multiplayercarddemo.appspot.com',
    measurementId: 'G-XXFYR01XQP',
  );
}
